from odoo import fields, models, api, _


class FuelStepLoad(models.Model):
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _name = 'lmm.fuel_step_load'
    _description = 'Fuel Step Load'

    name = fields.Char(
        required=True,
        string=_("Internal Id"),
        default="Autogenerated on Save",
        copy=False
    )

    fuel_load_division_id = fields.Many2one(
        comodel_name="lmm.fuel_load_division",
        required=False,
        string=_("Fuel Load Division"),
    )

    fuel_step = fields.Integer(
        string=_("Step"),
    )

    fuel_load = fields.Float(
        digits=(16, 9),
        string=_('Load')
    )

    fuel_loaded = fields.Float(
        digits=(16, 9),
        string=_('Loaded')
    )

    @api.model
    def create(self, vals):
        seq = self.env['ir.sequence'].next_by_code('lmm.fuel_step_load') or _('New')
        vals['name'] = seq
        return super(FuelStepLoad, self).create(vals)

    def copy(self, default=None):
        default = dict(default or {})

        copied_count = self.search_count(
            [('name', '=like', u"Copy of {}%".format(self.name))])
        if not copied_count:
            new_name = u"Copy of {}".format(self.name)
        else:
            new_name = u"Copy of {} ({})".format(self.name, copied_count)

        default['name'] = new_name
        return super(FuelStepLoad, self).copy(default)

    _sql_constraints = [
        ('name_unique',
         'UNIQUE(name)',
         "The fuel load step load id must be unique"),
    ]